### PR TITLE
created about page and setup store

### PR DESCRIPTION
**Pull request by larrythexu**

### CODE REVIEW

**Comment by larrythexu** [comment]
Weird bug - for some reason the image height squishes up the window height is decreased. This didn't happen with tindog

**Comment by awilli70** [comment]
Which page does this happen on?

**Comment by larrythexu** [comment]
nevermind, found the problem and fixed it!

**Comment by awilli70** [comment]
Styling looks awesome!

A couple of notes before we merge:
Add the about page to every sidebar nav and navbar; currently missing in index

Moving forward we have a few options:
If you feel comfortable tackling backend, I encourage you to go for it
Otherwise, reach out and we can schedule a time to do some virtual pair programming

**Comment by awilli70** [comment]
A couple of quick notes:

on mobile resolutions, the welcome to facebork on about.html is too large - should just need a media query and we're all good there
I'd recommend reverting the change to index.html for now - the page structure has changed pretty dramatically, so I'll probably have to go through and fix all of the navbars up.

**Pull request merged**
