### PR TITLE
Bmcder17

### PR DESCRIPTION
**Pull request by bmcder17**
I changed index.html to chat.html and created index.html as our home page.
I added the Patreon logo to the images folder and set up some basic styling rules for it (donation class in style.css). These rules are for inserting the logo anywhere except the nav bar and side nav bar. For those cases, the inherited styling works just fine.
I linked the Patreon logo with our Patreon donation page. 
I added some basic information text to the home page as well as additional hyperlinks to our other pages.
I created a slideshow for the home page that currently just pulls photos from a local folder, but will eventually pull from our mongo database.

### CODE REVIEW

**Comment by awilli70** [comment]
Looking mostly good!
I don't know if it is super necessary to have mongo integration on the home page (especially for the slideshow (image loading makes it super jank if it has to get it from an external source)

I'd recommend placing the entire index page text div within a div with class card so that the back of the page is white (then remove the background color of #info (black on blue is not super readable)

**Comment by awilli70** [comment]
Other notes: please add the home page to the navbar and sidenav, and the chat link in the sidenav still points to index

When the page gets too small, the patreon logo in the navbar is placed weirdly - add a media query for small window sizes that sets it to display:none

**Comment by bmcder17** [comment]
Got it. The patreon logo now disappears from the nav bar when the screen shrinks. The content in the text div is now all in a class card div and the #info background is gone. I updated the links for the nav bars to be correct and added a home option.

**Comment by awilli70** [comment]
Looks great!
The images are missing from the slideshow - once you upload those to the images folder I'll go ahead and merge it down.

**Comment by bmcder17** [comment]
Should be all set!

**Pull request merged**
